BooksProject/Controllers/BooksStoreController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using System.Net;
using System.Web.Script.Serialization;

namespace BooksProject.Controllers
{
    public class BooksStoreController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public JsonResult GetBookList()
        {
            var Url = "http://localhost:62902/api/Books";
            var json = new WebClient().DownloadString(Url);
            JavaScriptSerializer js = new JavaScriptSerializer();
            var model = js.Deserialize<dynamic>(json);
  
                return Json(new { Result = "Ok", Record = model });
     
            }

        public ActionResult GetAutor(int authorId) {

            var Url = "http://localhost:62902/api/Authors/books/" + authorId;
            var json = new WebClient().DownloadString(Url);
            JavaScriptSerializer js = new JavaScriptSerializer();
            var model = js.Deserialize<dynamic>(json);

            return PartialView("_GetAutor", Json(new { Result = "Ok", Record = model }));

        }




    }

}

BooksProject/Views/BooksStore/Index.cshtml
@{
    ViewBag.Title = "Tienda de Libros";
}

<div>
    <h1>Tienda de Libros - Practica</h1>
</div>
<br />
<div class="row">
    <div class="container">
        <table id="TblBooksList" class="table table-striped table-bordered" style="width:100% !important"></table>

    </div>
</div>

BooksProject/Views/BooksStore/_GetAutor.cshtml
<div class="container">
    <h2>Pendiente de Popular</h2>
</div>

BooksProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Libreria", "Index", "BooksStore", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>*@
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            @*<p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>*@
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)

    <!--BoostrapMessage-->
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog modal-lg" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel"></h4>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" id="btnClose" class="btn btn-default" data-dismiss="modal">Cerrar</button>
                    <button type="button" id="btnOk" class="btn btn-primary">Ok</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Small modal -->
    <div id="myModalSmall" class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                </div>
                <div class="modal-body">
                    ...
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Ok</button>
                </div>
            </div>
        </div>
    </div>
    <!-- Confirm modal -->
    <div class="modal fade" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true" id="ConfirmModal">
        <div class="modal-dialog modal-sm">
            <div class="modal-content">
                <div class="modal-headerConfirm">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">&nbsp;Confirmaci&oacute;n</h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">

                    @*<i class="fa fa-check-circle">&nbsp;&nbsp;&nbsp;</i>*@

                    <button type="button" class="btn btn-primary" id="modal-btn-si"><i class="fa fa-thumbs-o-up"> Si</i></button>
                    <button type="button" class="btn btn-warning" id="modal-btn-no"><i class="fa fa-thumbs-o-down"> No</i></button>
                </div>
            </div>
        </div>
    </div>
</body>
</html>